apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbcaller.fullname" . }}
  labels:
    {{- include "dbcaller.labels" . | nindent 4 }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      {{- include "dbcaller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
         {{- include "dbcaller.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: dbcaller:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          volumeMounts:
            - name: app-settings-volume
              mountPath: /src/appsettings.json  # Mount at the path where appsettings.json is expected
              subPath: appsettings.json       # Ensures that the file is mounted as appsettings.json
      volumes:
        - name: app-settings-volume
          configMap:
            name: appsettings-config  # Reference to the ConfigMap we created
