apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbcaller.fullname" . }}
  labels:
    {{- include "dbcaller.labels" . | nindent 4 }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      {{- include "dbcaller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
         {{- include "dbcaller.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: dbcaller
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

