apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbcaller.name" . }}
  labels:
    {{- include "dbcaller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "dbcaller.selectorLabels" . | nindent 4 }}
